### ISSUE TITLE
Crash when removing a seat

### ISSUE THREAD

**Issue by lbonn** [Smithay/smithay-clipboard#53]
On sway, reloading the configuration after removing a seat from the configuration causes a panic in the clipboard worker (logs from the example application):

```
wl_display@1: error 0: invalid object 31
Io error: Invalid argument (os error 22)
thread 'smithay-clipboard' panicked at src/worker.rs:98:47:
called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
stack backtrace:
Unset keyboard capability
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: smithay_clipboard::worker::worker_impl
             at ./src/worker.rs:98:9
   5: smithay_clipboard::worker::spawn::{{closure}}
             at ./src/worker.rs:23:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Window configured to: WindowConfigure { new_size: (Some(1916), Some(1053)), suggested_bounds: None, decoration_mode: Server, state: WindowState(TILED_LEFT | TILED_RIGHT | TILED_TOP | TILED_BOTTOM), capabilities: WindowManagerCapabilities(WINDOW_MENU | MAXIMIZE | FULLSCREEN | MINIMIZE) }
Io error: Invalid argument (os error 22)
Error trying to flush the wayland display: Invalid argument (os error 22)
thread 'main' panicked at examples/clipboard.rs:76:55:
called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: clipboard::main
             at ./examples/clipboard.rs:76:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

First spotted on alacritty which also crashes

**Comment by kchibisov** [comment]
Could you post the whole `WAYLAND_DEBUG=1 alacritty -vv` log?

**Comment by lbonn** [comment]
@kchibisov https://gist.github.com/lbonn/d76caab4b0caf132be70188458158f12

EDIT: ah sorry, this is only the example from this repo, I'll get another log from alacritty with `-vv`

**Comment by kchibisov** [comment]
I think it's a sway bug since I can't win the race with it?

**Comment by kchibisov** [comment]
Could you try this

```diff
diff --git a/src/state.rs b/src/state.rs
index 69921e9..50a9577 100644
--- a/src/state.rs
+++ b/src/state.rs
@@ -356,7 +356,10 @@ impl SeatHandler for State {
     }

     fn remove_seat(&mut self, _: &Connection, _: &QueueHandle<Self>, seat: WlSeat) {
-        self.seats.remove(&seat.id());
+        if let Some(mut seat) = self.seats.remove(&seat.id()) {
+            // Mark the seat as destroyed so we don't try to cleanup the objects.
+            seat.destroyed = true;
+        }
     }
 }

@@ -553,6 +556,7 @@ struct ClipboardSeatState {
     data_device: Option<DataDevice>,
     primary_device: Option<PrimarySelectionDevice>,
     has_focus: bool,
+    destroyed: bool,

     /// The latest serial used to set the selection content.
     latest_serial: u32,
@@ -560,6 +564,11 @@ struct ClipboardSeatState {

 impl Drop for ClipboardSeatState {
     fn drop(&mut self) {
+        // When the seat got explicitly destroyed don't run destructors.
+        if self.destroyed {
+            return;
+        }
+
         if let Some(keyboard) = self.keyboard.take() {
             if keyboard.version() >= 3 {
                 keyboard.release();

```

**Comment by kchibisov** [comment]
@lbonn example is fine, I thought you were reporting for alacritty.

**Comment by lbonn** [comment]
It crashes the same way with the patch.

```
...
[ 105070.811] wl_display@1.error(wl_display@1, 0, "invalid object 31")
wl_display@1: error 0: invalid object 31
Io error: Invalid argument (os error 22)
thread 'smithay-clipboard' panicked at src/worker.rs:98:47:
called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Unset keyboard capability
Window configured to: WindowConfigure { new_size: (Some(1916), Some(1053)), suggested_bounds: None, decoration_mode: Server, state: WindowState(TILED_LEFT | TILED_RIGHT | TILED_TOP | TILED_BOTTOM), capabilities: WindowManagerCapabilities(WINDOW_MENU | MAXIMIZE | FULLSCREEN | MINIMIZE) }
Io error: Invalid argument (os error 22)
Error trying to flush the wayland display: Invalid argument (os error 22)
thread 'main' panicked at examples/clipboard.rs:76:55:
called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
```

There may be a sway bug somewhere, I am just trying multi-seat right now and some other things are weird. However, kitty and firefox keep running after this.

The worker loop needs to restart maybe?

Not sure if the `invalid object` message is relevant, object 31 is `wp_viewporter`...

I'll try to have a look at what sway is doing when reloading a configuration.

**Comment by kchibisov** [comment]
Could you post the `WAYLAND_DEBUG=1` log with my `patch` actually and also could you tell apply that?

```diff
diff --git a/src/state.rs b/src/state.rs
index 69921e9..891e45e 100644
--- a/src/state.rs
+++ b/src/state.rs
@@ -283,6 +283,7 @@ impl SeatHandler for State {
     }
 
     fn new_seat(&mut self, _: &Connection, _: &QueueHandle<Self>, seat: WlSeat) {
+        println!("New seat");
         self.seats.insert(seat.id(), Default::default());
     }
 
@@ -293,6 +294,7 @@ impl SeatHandler for State {
         seat: WlSeat,
         capability: Capability,
     ) {
+        println!("New capability");
         let seat_state = self.seats.get_mut(&seat.id()).unwrap();
 
         match capability {
@@ -332,6 +334,7 @@ impl SeatHandler for State {
         seat: WlSeat,
         capability: Capability,
     ) {
+        println!("Removing capability");
         let seat_state = self.seats.get_mut(&seat.id()).unwrap();
         match capability {
             Capability::Keyboard => {
@@ -356,7 +359,11 @@ impl SeatHandler for State {
     }
 
     fn remove_seat(&mut self, _: &Connection, _: &QueueHandle<Self>, seat: WlSeat) {
-        self.seats.remove(&seat.id());
+        println!("Removing the seat");
+        if let Some(mut seat) = self.seats.remove(&seat.id()) {
+            // Mark the seat as destroyed so we don't try to cleanup the objects.
+            seat.destroyed = true;
+        }
     }
 }
 
@@ -553,6 +560,7 @@ struct ClipboardSeatState {
     data_device: Option<DataDevice>,
     primary_device: Option<PrimarySelectionDevice>,
     has_focus: bool,
+    destroyed: bool,
 
     /// The latest serial used to set the selection content.
     latest_serial: u32,
@@ -560,6 +568,11 @@ struct ClipboardSeatState {
 
 impl Drop for ClipboardSeatState {
     fn drop(&mut self) {
+        // When the seat got explicitly destroyed don't run destructors.
+        if self.destroyed {
+            return;
+        }
+
         if let Some(keyboard) = self.keyboard.take() {
             if keyboard.version() >= 3 {
                 keyboard.release();

```

I think it's just a race which we can't win, some clients are more lucky here.

**Comment by lbonn** [comment]
@kchibisov https://gist.github.com/lbonn/55246592d5852d86ce9e1498900f4ec5

**Comment by kchibisov** [comment]
Yeah, I can't win the race as you can see, because once you remove the capability the object is not yet destroyed in code. Some clients which don't release pointer could survive, but I'm not sure I can.

In general sway should give a grace period for stuff like that.

See the https://gitlab.freedesktop.org/wayland/wayland/-/issues/10
